### ISSUE TITLE
Render markdown for JSDoc

### ISSUE THREAD

**Issue by bartlomieju** [bartlomieju/deno_doc#10]
JSDoc can contain markdown snippets with example. They should be rendered accordingly. It will require to pre-parse and clean JSDoc in Rust to get rid of comment markers (`*`). Note to self: whitespaces should be preserved.

**Comment by lucacasonato** [comment]
I have  branch that makes that work in the frontend. Cleaned stuff from the backend would be appreciated though. I'll PR this in a minute.
