### ISSUE TITLE
Remove snippets

### ISSUE THREAD

**Issue by lucacasonato** [bartlomieju/deno_doc#14]
I feel like we should try to get rid of the snippets underneath the name, but retain all of their useful information. They take up space and contain useless words like `export`. 

I would prefer if this:
![image](https://user-images.githubusercontent.com/7829205/77345470-f38c3300-6d34-11ea-9d49-5f8f06d0f632.png)

looked like this:
![image](https://user-images.githubusercontent.com/7829205/77345625-33ebb100-6d35-11ea-89a8-8818011d4181.png)

This would also allow for clicking thru to the implemented types (if that is needed).

Also this could be used to display for example the abstract keyword if a class is abstract.

**Comment by bartlomieju** [comment]
Yeah, definitely. I used snippets to get some output quickly. We should remove all of them as we serialize more data👍

**Comment by bartlomieju** [comment]
Update: snippets are no longer shown in the web page; they're still in JSON output though (to be removed)

**Comment by bartlomieju** [comment]
Removed in https://github.com/bartlomieju/deno_doc/pull/25
