### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by lucacasonato** [bartlomieju/deno_doc#24]
Here is what I'm imagining:

#### `deno_doc test.ts`
```
const fizzBuzz: string
    Something about fizzBuzz

function foo(a: string, b: number): void
    Hello there, this is a multiline JSdoc.
    It has many lines
    Or not that many?

class Foobar
    Class doc

interface Reader

type NumberArray

namespace Deno
```

#### `deno_doc test.ts --format json`
```
{ ... }
```

#### `deno_doc test.ts --format json --output docs.json`
Places the generated json to a file at docs.json rather than to stdout

#### `deno_doc test.ts --format html --output docs`
Generates a `docs` folder with the precompiled React application and the generated docs.json.

`--output` has to be specified.

#### `deno_doc test.ts fizzBuzz`
```
Defined in test.ts:7:0

const fizzBuzz: string
    Something about fizzBuzz
```

#### `deno_doc test.ts fizzBuzz --format json`
```
{
    "kind": "variable",
    "name": "fizzBuzz",
    "snippet": "export const fizzBuzz: string = \"fizzBuzz\";",
    "location": { "filename": "test.ts", "line": 7, "col": 0 },
    "jsDoc": "Something about fizzBuzz",
    "variableDef": {
      "tsType": { "repr": "string", "kind": "keyword", "keyword": "string" },
      "kind": "const"
    }
}
```

#### `deno_doc test.ts foo`
```
Defined in test.ts:23:0

function foo(a: string, b: number): void
    Hello there, this is a multiline JSdoc.
    It has many lines
    Or not that many?
```

#### `deno_doc test.ts Foobar`
```
Defined in test.ts:33:0

class Foobar
    Class doc

constructor constructor(name: string)
property protected protected1: number
property public public1: boolean
property public2: number
method foo(): Promise<void>
method bar(): void
    Sync bar method
```

#### `deno_doc test.ts Foobar.bar`
```
Defined in test.ts:36:0

bar(): void
    Sync bar method
```

ect... - the "titles" should match the titles on the webpage, and the "body" should look similar to the  card content on the webpage.

Everything should be nicely colored.

This is similar to how Go displays things. 

Ideas?

/cc @bartlomieju

**Comment by bartlomieju** [comment]
> Here is what I'm imagining:
> 
> #### `deno_doc test.ts`
> ```
> const fizzBuzz: string
>     Something about fizzBuzz
> 
> function foo(a: string, b: number): void
>     Hello there, this is a multiline JSdoc.
>     It has many lines
>     Or not that many?
> 
> class Foobar
>     Class doc
> 
> interface Reader
> 
> type NumberArray
> 
> namespace Deno
> ```
> 
> #### `deno_doc test.ts --format json`
> ```
> { ... }
> ```

Ok


> #### `deno_doc test.ts --format json --output docs.json`
> Places the generated json to a file at docs.json rather than to stdout

Let's skip this one, in Deno we prefer piping to `--output` arg

> #### `deno_doc test.ts --format html --output docs`
> Generates a `docs` folder with the precompiled React application and the generated docs.json.
> 
> `--output` has to be specified.
> 

Let's skip this one as well, we'll need to figure out how to provide HTML output in Deno, for now we can keep frontend separated .

> #### `deno_doc test.ts fizzBuzz`
> ```
> Defined in test.ts:7:0
> 
> const fizzBuzz: string
>     Something about fizzBuzz
> ```

Ok

> #### `deno_doc test.ts fizzBuzz --format json`
> ```
> {
>     "kind": "variable",
>     "name": "fizzBuzz",
>     "snippet": "export const fizzBuzz: string = \"fizzBuzz\";",
>     "location": { "filename": "test.ts", "line": 7, "col": 0 },
>     "jsDoc": "Something about fizzBuzz",
>     "variableDef": {
>       "tsType": { "repr": "string", "kind": "keyword", "keyword": "string" },
>       "kind": "const"
>     }
> }
> ```


Let's skip single JSON output for now.

> #### `deno_doc test.ts foo`
> ```
> Defined in test.ts:23:0
> 
> function foo(a: string, b: number): void
>     Hello there, this is a multiline JSdoc.
>     It has many lines
>     Or not that many?
> ```
> 
> #### `deno_doc test.ts Foobar`
> ```
> Defined in test.ts:33:0
> 
> class Foobar
>     Class doc
> 
> constructor constructor(name: string)
> property protected protected1: number
> property public public1: boolean
> property public2: number
> method foo(): Promise<void>
> method bar(): void
>     Sync bar method
> ```
> 
> #### `deno_doc test.ts Foobar.bar`
> ```
> Defined in test.ts:36:0
> 
> bar(): void
>     Sync bar method
> ```

Sounds good

> ect... - the "titles" should match the titles on the webpage, and the "body" should look similar to the card content on the webpage.
> 
> Everything should be nicely colored.
> 
> This is similar to how Go displays things.
> 
> Ideas?
> 
> /cc @bartlomieju

Yeah I agree, coloring is nice, but not necessary for first pass (also it must be optional to honor `NO_COLOR` env var).

**Comment by ry** [comment]
I think colors for the text output would be nice - but it should be tested on both light and dark backgrounds. Maybe just using bold/underline is best.

**Comment by lucacasonato** [comment]
Implemented in deno
