### ISSUE TITLE
Simple frontend setup

### ISSUE THREAD

**Issue by bartlomieju** [bartlomieju/deno_doc#3]
To consume JSON output we should have some kind of web frontend, while the ultimate goal is to replace Typedoc in [Deno API reference](https://deno.land/typedoc/). 

Let's start small with basic setup and separate components for different kind of docs:
https://github.com/bartlomieju/deno_doc/blob/d6dd7d80bf2ebec306594835d83a28d64c7ac88f/src/doc/mod.rs#L5-L15

All top level objects in JSON output are `DocNode` structs:
https://github.com/bartlomieju/deno_doc/blob/d6dd7d80bf2ebec306594835d83a28d64c7ac88f/src/doc/mod.rs#L144-L173

Since I'm iterating heavily on the schema of JSON, we can assume that first five fields are shared by all kinds of structs, others are dependent on the kind (and will change heavily). 

I did super small webpage in Vue for debugging purposes; it can be seen in `script.js` and `index.html` files.

CC @lucacasonato

**Comment by lucacasonato** [comment]
Looks good. A few questions:
1. Is there one JSON file per page or one for everything?
2. Should this be part of deno_website2 or a standalone webapp?
3. Should this be more like pkg.go.dev (everything on one page), or be multi page like deno.land/typedoc or pub.dev/documentation/path/latest/? I prefer the multi page view.

**Comment by bartlomieju** [comment]
> Looks good. A few questions:
> 
> 1. Is there one JSON file per page or one for everything?

Not sure what you mean; for one entry point there is a single JSON (with top level array) produced (`cargo run test.ts > test.data.json`).

> 2. Should this be part of deno_website2 or a standalone webapp?

Standalone, I'd be great if we could run it using Deno directly, but for pass anything goes.

> 3. Should this be more like pkg.go.dev (everything on one page), or be multi page like deno.land/typedoc or pub.dev/documentation/path/latest/? I prefer the multi page view.

Whichever you prefer, we'll iterate on it multiple times anyway; so what's easier to get off the ground is best.

**Comment by bartlomieju** [comment]
@lucacasonato did an awesome job, by providing a React frontend. Closing this issue for now, as we already have a "patient" to operate (iterate) on 😅
