### ISSUE TITLE
Frontend singlepage update

### ISSUE THREAD

**Issue by bartlomieju** [bartlomieju/deno_doc#8]
Some thoughts about single page view

a) scrollable sidebar with list of all nodes (ie. should scroll independent of the rest of page)

b) <s>table of contents; first element visible on the page, all nodes grouped per node kind, all nodes linked to respective card</s> actually not needed, all of that should be in the sidebar

c) node card: current structure looks good, but each card should have an additional child component dependent on node kind, that way, we can customize display for each node

CC @lucacasonato

**Comment by lucacasonato** [comment]
Things that should be displayed for individual types:

#### Classes
Constructors with JSDoc, location and params, visibility
Properties with JSDoc, location and return type, visibility, read/write
Methods with JSDoc, location and params. return type, visibility, getter/setter

#### Variables
read/write
return type

#### Functions
params
returm type

#### Enums
Keys and values

#### Interfaces
?

#### Type Aliases
type definition?

#### Namespaces
_should these even be displayed?_

**Comment by bartlomieju** [comment]
> Enums
Keys and values

Values are not yet added

> Interfaces
?

I started working on interfaces, added `methods` field to `interfaceDef`

> Type Aliases
type definition?

Sounds good

> Namespaces
should these even be displayed?

I guess we can skip that for now.

**Comment by bartlomieju** [comment]
@lucacasonato I've added properties and call signature to interface definition. That should cover all interface variants in `Deno` namespace
